<?php
/**
 */
?>
<div class="pages">
<ol>
<?php if (!$this->isFirstPage()): ?>
    <li><a class="previous ajax notloaded" href="<?php echo $this->getPreviousPageUrl() ?>" title="<?php echo $this->__('Previous') ?>"><img src="<?php echo $this->getSkinUrl('images/pager_arrow_left.gif') ?>" alt="<?php echo $this->__('Previous') ?>" class="v-middle" /></a></li>
<?php endif;?>

<?php if ($this->canShowFirst()): ?>
    <li><a class="first ajax notloaded" href="<?php echo $this->getFirstPageUrl() ?>">1</a></li>
<?php endif;?>

<?php if ($this->canShowPreviousJump()): ?>
    <li><a id="previous_jump" class="previous_jump ajax notloaded" title="" href="<?php echo $this->getPreviousJumpUrl() ?>">...</a></li>
<?php endif;?>

<?php foreach ($this->getFramePages() as $_page): ?>
    <?php if ($this->isPageCurrent($_page)): ?>
        <li class="current"><?php echo $_page ?></li>
    <?php else: ?>
        <li><a class="ajax notloaded" href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
    <?php endif;?>
<?php endforeach;?>

<?php if ($this->canShowNextJump()): ?>
    <li><a class="next_jump ajax notloaded" title="" href="<?php echo $this->getNextJumpUrl() ?>">...</a></li>
<?php endif;?>

<?php if ($this->canShowLast()): ?>
  <li><a class="last ajax notloaded" href="<?php echo $this->getLastPageUrl() ?>"><?php echo $this->getLastPageNum() ?></a><li>
<?php endif;?>

<?php if (!$this->isLastPage()): ?>
    <li><a class="next ajax notloaded" href="<?php echo $this->getNextPageUrl() ?>" title="<?php echo $this->__('Next') ?>"><img src="<?php echo $this->getSkinUrl('images/pager_arrow_right.gif') ?>" alt="<?php echo $this->__('Next') ?>" class="v-middle" /></a></li>
<?php endif;?>
</ol>
	<div id="loadingmask_pager" style="display: none;">
		<div class="loader" id="loading-mask-loader"><img src="<?php echo $this->getSkinUrl("images/opc-ajax-loader.gif")?>" alt="<?php echo $this->__('Loading...') ?>"/><?php echo $this->__('Loading...') ?></div>
		<div id="loading-mask"></div>
	</div>
</div>