<?php echo $this->helper('adminhtml/media_js')->includeScript('coobus/media/uploader/jsuploader.js') ?>
<?php echo $this->helper('adminhtml/media_js')->includeScript('coobus/media/uploader/uploader.js') ?>
<?php echo $this->helper('adminhtml/media_js')->includeScript('lib/flex.js') ?>
<?php echo $this->helper('adminhtml/media_js')->includeScript('mage/adminhtml/flexuploader.js') ?>
<?php echo $this->helper('adminhtml/media_js')->includeScript('lib/FABridge.js') ?>
<?php echo $this->helper('adminhtml/media_js')->getTranslatorScript() ?>

<div id="uploaderSelection">
<input type="radio" id="uploader-type-multiple" class="uploader-type" name="uploaderType" checked value="multiple"/>&nbsp;<label for="uploaderType">Carregar m&uacute;ltiplas imagens</label><br/>
<input type="radio" id="uploader-type-unique" class="uploader-type" name="uploaderType" value="unique"/>&nbsp;<label for="uploaderType">Carregar uma imagem por vez</label>
</div>
<div id="<?php echo $this->getHtmlId() ?>" class="uploader">
    <div class="buttons" style="position:relative;float:right;">
        <?php /* buttons included in flex object */ ?>
        <?php  /*echo $this->getBrowseButtonHtml()*/  ?>
        <?php  /*echo $this->getUploadButtonHtml()*/  ?>
        <div id="<?php echo $this->getHtmlId() ?>-install-flash" style="display:none">
            <?php echo Mage::helper('media')->__('This content requires last version of Adobe Flash Player. <a href="%s">Get Flash</a>', 'http://www.adobe.com/go/getflash/') ?>
        </div>
        <div class="unique" style="display:none;">
	        <div class="no-display" id="<?php echo $this->getHtmlId() ?>-uploadBlockTemplate">
	        	<div id="uploadBlock-{{id}}">
	                <form action="{{url}}" enctype="multipart/form-data" encoding="multipart/form-data" method="post" target="uploadBlockIframe-{{id}}">
	                    <input type="file" name="image"/>
	                    <input type="hidden" name="Filename"/>
	                    <input type="hidden" name="form_key" value="{{formKey}}"/>
	                    <input type="hidden" name="Upload" value="Submit Query"/>
	                </form>
	                <iframe name="uploadBlockIframe-{{id}}" style="display:none;"></iframe>
	            </div></div>
			<div id="uploadBlocks" style="float:left;margin-right: 0.5em;"></div>
			<?php echo $this->getUploadButtonHtml() ?>
        </div>
    </div>
    <div class="clear"></div>
    <div class="no-display" id="<?php echo $this->getHtmlId() ?>-template">
        <div id="{{id}}" class="file-row">
        <span class="file-info">{{name}}<?php /* ({{size}})*/?></span>
        <span class="delete-button"><?php echo $this->getDeleteButtonHtml() ?></span>
        <span class="progress-text"></span>
        <div class="clear"></div>
        </div>
    </div><?php /*
    <div class="no-display" id="<?php echo $this->getHtmlId() ?>-template-progress">
        {{percent}}% {{uploaded}} / {{total}}
    </div>*/?>
</div>
<script type="text/javascript">
//<![CDATA[
                                                           
<?php echo $this->getJsObjectName() ?> = new JsUploader('<?php echo $this->getHtmlId() ?>', <?php echo $this->getConfigJson() ?>);
//<?php echo $this->getJsObjectName() ?>.addListener('select',<?php echo $this->getJsObjectName() ?>.upload);

var maxUploadFileSizeInBytes = <?php echo $this->getDataMaxSizeInBytes() ?>;
var maxUploadFileSize = '<?php echo $this->getDataMaxSize() ?>';

//<?php echo $this->getJsObjectName() ?>_multiple = new Flex.Uploader('<?php echo $this->getHtmlId() ?>', '<?php echo $this->getUploaderUrl('media/uploader.swf') ?>', <?php echo $this->getConfigJson() ?>);

function uploaderSelection(event) {
    if ( Event.element(event).value == 'multiple' ){
    	$$('.unique')[0].hide(); 
    	$$('.flex')[0].show();
    }else{
    	$$('.unique')[0].show();
    	$$('.flex')[0].hide();
    }
}
if ( !$$('.flex') ){
	$('uploaderSelection').hide();
	$$('.unique')[0].show();
}
$('uploader-type-multiple').observe('change', uploaderSelection);
$('uploader-type-unique').observe('change', uploaderSelection);

if (varienGlobalEvents) {
//    varienGlobalEvents.attachEventHandler('tabChangeBefore', <?php echo $this->getJsObjectName() ?>_multiple.onContainerHideBefore);
}
//]]>
</script>