<?php
/**
 *
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if( $_productCollection && !$_productCollection->count() ): ?>
<?php else: ?>

<div id="product-grid" class="category-products">
    <?php if ( $this->isToolbarTopEnabled() ) echo $this->getToolbarHtml(); ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <?php if($_product->isSaleable()): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resized($this->getThumbWidth(),null, $this->getThumbRatio())->scale('center',$this->getThumbRatio()); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
	        		<?php foreach ($_product->getAttributes() as $_attributeCode => $_attribute){
				            if ($_attribute->getIsUserDefined() && $_attribute->getIsVisibleOnFront() && $_product->hasData($_attributeCode)): ?>
					<h3 class="attribute <?php echo $_attributeCode;?>"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getData($_attributeCode), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getData($_attributeCode), $_attributeCode); ?></a></h3>
					<?php 	endif;} ?>
                    <?php echo $this->getPriceHtml($_product, true, '-new') ?>
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>

                </div>
            </div>
        </li>
	<?php endif; ?>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = 3; #$this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resized($this->getThumbWidth(),null, $this->getThumbRatio())->scale('center',$this->getThumbRatio()); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>        
        		<?php foreach ($_product->getAttributes() as $_attributeCode => $_attribute){
			            if ($_attribute->getIsUserDefined() && $_attribute->getIsVisibleOnFront() && $_product->hasData($_attributeCode)): ?>
				<h3 class="attribute <?php echo $_attributeCode;?>"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getData($_attributeCode), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getData($_attributeCode), $_attributeCode); ?></a></h3>
				<?php 	endif;} ?>
                <?php echo $this->getPriceHtml($_product, false) ?>
<?php if($_product->getSpecialPrice() != ''): ?>
<div class="price-box"><p class="black-friday-price"><span class="price-label">Black Friday:</span><span class="price">
<?php echo Mage::helper('core')->currency(number_format($_product->getSpecialPrice()*0.85,2)) ?>
</span></p></div>
<?php else: ?>
<div class="price-box"><p class="black-friday-price"><span class="price-label">Black Friday:</span><span class="price">
<?php echo Mage::helper('core')->currency(number_format($_product->getPrice()*0.85,2)) ?>
</span></p></div>
<?php endif ?>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
    <?php endif; ?>
</div>
<?php endif; ?>
